/**
 * TBRAC Assessment Data — 10 modules × 10 criteria each.
 * All questions scored 0–10: 0 = high risk / non-compliant, 10 = low risk / fully compliant.
 * Matches mechanism.md exactly.
 */

export interface Question {
  id: string
  text: string
  text_zh: string
  anchor_low: string
  anchor_low_zh: string
  anchor_high: string
  anchor_high_zh: string
  document_hint?: string
}

export interface Module {
  key: string
  number: number
  name: string
  name_zh: string
  icon: string
  description: string
  description_zh: string
  document_types: string[]
  questions: Question[]
}

export const ASSESSMENT_MODULES: Module[] = [
  {
    key: "regulatory_scrutiny",
    number: 1,
    name: "Regulatory Scrutiny",
    name_zh: "监管审查",
    icon: "Shield",
    description: "CFIUS reviews, export controls, blacklist status, and sector-specific compliance",
    description_zh: "CFIUS审查、出口管制、黑名单状态及行业合规性",
    document_types: [
      "Mandatory CFIUS filing status",
      "Export Control Classification Numbers (ECCN)",
      "Records of CCP Party Committee presence in governance",
      "Proof of U.S. licensing completeness (FDA, FCC approvals)",
    ],
    questions: [
      {
        id: "m1_q1",
        text: "CFIUS Risk Exposure: What is the nature of your U.S. transaction and existing government ties?",
        text_zh: "CFIUS风险敞口：您在美国的交易性质及现有政府关联如何？",
        anchor_low: "Blocked/mandatory CFIUS filing",
        anchor_low_zh: "被拦截/强制CFIUS申报",
        anchor_high: "Low risk / pre-filing clearance obtained",
        anchor_high_zh: "低风险/已获预申报许可",
        document_hint: "Prior CFIUS filing outcomes or pre-filing correspondence",
      },
      {
        id: "m1_q2",
        text: "Export Control Risk: Are your products classified under EAR or ITAR, and do you export controlled U.S. components?",
        text_zh: "出口管制风险：您的产品是否受EAR或ITAR管制，是否出口受控美国零部件？",
        anchor_low: "Uses restricted tech without controls",
        anchor_low_zh: "使用受限技术且无管控措施",
        anchor_high: "No U.S.-origin controlled content",
        anchor_high_zh: "不含任何美国受控内容",
        document_hint: "Export Control Classification Number (ECCN) determination",
      },
      {
        id: "m1_q3",
        text: "Entity List / Sanctions Status: Are you, your subsidiaries, or partners on the BIS Entity List, OFAC SDN, or MEU list?",
        text_zh: "实体清单/制裁状态：您、子公司或合作伙伴是否在BIS实体清单、OFAC SDN或MEU名单上？",
        anchor_low: "Listed on SDN or MEU list",
        anchor_low_zh: "列于SDN或MEU名单",
        anchor_high: "No exposure to any restricted list",
        anchor_high_zh: "未出现在任何限制名单上",
        document_hint: "Sanctions screening report",
      },
      {
        id: "m1_q4",
        text: "National Security Sector: Does your core product belong to a high-risk sector (AI, 5G, biotech, semiconductors)?",
        text_zh: "国家安全行业：您的核心产品是否属于高风险行业（人工智能、5G、生物技术、半导体）？",
        anchor_low: "Core product in highest-risk sector",
        anchor_low_zh: "核心产品处于最高风险行业",
        anchor_high: "Non-sensitive consumer industry",
        anchor_high_zh: "非敏感消费品行业",
        document_hint: "Product description and sector classification",
      },
      {
        id: "m1_q5",
        text: "Ownership Transparency: Is there a CCP committee at board level, or does a state-owned enterprise hold a significant stake?",
        text_zh: "所有权透明度：董事会层面是否设有中共党委，或国有企业是否持有重大股份？",
        anchor_low: "State-owned with CCP party committee",
        anchor_low_zh: "国有且设有中共党委",
        anchor_high: "Fully private with transparent ownership",
        anchor_high_zh: "完全私营且所有权透明",
        document_hint: "Corporate ownership chart, shareholder registry",
      },
      {
        id: "m1_q6",
        text: "Data Sovereignty: Do you transfer sensitive U.S. data to China, or is it stored on U.S.-based servers?",
        text_zh: "数据主权：您是否将敏感美国数据传输至中国，或存储于美国境内服务器？",
        anchor_low: "U.S. data transferred to China",
        anchor_low_zh: "美国数据被传输至中国",
        anchor_high: "All U.S. data localized on U.S.-based servers",
        anchor_high_zh: "所有美国数据存储于美国境内服务器",
        document_hint: "Data flow diagram, cloud infrastructure documentation",
      },
      {
        id: "m1_q7",
        text: "U.S. Licensing: Have you obtained all required sector-specific U.S. certifications (e.g., FDA, FCC, FAA)?",
        text_zh: "美国许可证：您是否已获得所有必要的行业专属美国认证（如FDA、FCC、FAA）？",
        anchor_low: "Lacks required licenses",
        anchor_low_zh: "缺少必要许可证",
        anchor_high: "Fully certified for all applicable sectors",
        anchor_high_zh: "所有适用行业均已获得完整认证",
        document_hint: "Current U.S. regulatory certifications",
      },
      {
        id: "m1_q8",
        text: "Political / Media Sensitivity: Is your company or industry currently targeted in U.S. congressional hearings or political debate?",
        text_zh: "政治/媒体敏感性：您的公司或行业当前是否成为美国国会听证或政治辩论的目标？",
        anchor_low: "Actively targeted in hearings",
        anchor_low_zh: "正积极被听证会针对",
        anchor_high: "No political or media concern",
        anchor_high_zh: "无任何政治或媒体关注",
        document_hint: "Media monitoring report",
      },
      {
        id: "m1_q9",
        text: "Legal Track Record: Do you have a history of U.S. lawsuits, IP theft accusations, or trade litigation?",
        text_zh: "法律记录：您是否有美国诉讼、知识产权盗窃指控或贸易诉讼的历史？",
        anchor_low: "Sanctioned or sued for IP theft",
        anchor_low_zh: "因知识产权盗窃被制裁或起诉",
        anchor_high: "Clean legal track record",
        anchor_high_zh: "法律记录清洁",
        document_hint: "Litigation history summary",
      },
      {
        id: "m1_q10",
        text: "U.S. Entry Strategy: Is your U.S. entity incorporated in the U.S. with an independently governed structure?",
        text_zh: "美国进入策略：您的美国实体是否在美国注册并具有独立治理结构？",
        anchor_low: "Opaque, Chinese-controlled U.S. entity",
        anchor_low_zh: "不透明、中方控制的美国实体",
        anchor_high: "Independent U.S. governance structure",
        anchor_high_zh: "独立的美国治理结构",
        document_hint: "U.S. corporate charter, board composition",
      },
    ],
  },
  {
    key: "political_geopolitical",
    number: 2,
    name: "Political & Geopolitical Risk",
    name_zh: "政治与地缘政治风险",
    icon: "Globe",
    description: "Sanctions monitoring, bilateral climate, legislative threats, and lobbying practices",
    description_zh: "制裁监控、双边关系、立法威胁及游说实践",
    document_types: [
      "Lobbying and transparency practice filings",
      "Documentation of affiliations with Chinese government or military",
      "FARA (Foreign Agents Registration Act) registration status",
    ],
    questions: [
      {
        id: "m2_q1",
        text: "Sanctions / Blacklist: Do you have a system to regularly monitor inclusion on OFAC, BIS, FCC, or DoD restricted lists?",
        text_zh: "制裁/黑名单：您是否有系统定期监控是否被列入OFAC、BIS、FCC或国防部限制名单？",
        anchor_low: "On multiple restricted lists",
        anchor_low_zh: "列于多个限制名单",
        anchor_high: "No exposure; automated monitoring in place",
        anchor_high_zh: "无风险敞口；已部署自动监控系统",
        document_hint: "Sanctions monitoring system documentation",
      },
      {
        id: "m2_q2",
        text: "CFIUS Probability: Is your business located near sensitive U.S. sites, or do you have access to critical infrastructure data?",
        text_zh: "CFIUS概率：您的业务是否位于美国敏感地点附近，或能否访问关键基础设施数据？",
        anchor_low: "Mandatory CFIUS filing / objection expected",
        anchor_low_zh: "预计须强制申报CFIUS/将遭反对",
        anchor_high: "Historically cleared with no proximity issues",
        anchor_high_zh: "历史上均已通过审查且无邻近问题",
        document_hint: "Facility location maps, infrastructure access records",
      },
      {
        id: "m2_q3",
        text: "Sector Sensitivity: How sensitive is your sector from a national security standpoint?",
        text_zh: "行业敏感性：从国家安全角度看，您所在行业的敏感程度如何？",
        anchor_low: "Dual-use / military technology",
        anchor_low_zh: "两用/军事技术",
        anchor_high: "Retail / consumer products only",
        anchor_high_zh: "仅零售/消费品",
      },
      {
        id: "m2_q4",
        text: "Bilateral Climate: How do current U.S.–China diplomatic tensions and trade talks impact your business model?",
        text_zh: "双边关系：当前中美外交紧张及贸易谈判对您的商业模式有何影响？",
        anchor_low: "High tension / active trade war directly impacts operations",
        anchor_low_zh: "高度紧张/贸易战直接影响运营",
        anchor_high: "Diplomatic stability; minimal direct impact",
        anchor_high_zh: "外交稳定；直接影响极小",
      },
      {
        id: "m2_q5",
        text: "Legislative Threats: Is your company or sector specifically named in pending U.S. legislation (e.g., RESTRICT Act, CHIPS Act)?",
        text_zh: "立法威胁：您的公司或行业是否被美国待审立法（如《限制法》《芯片法》）明确点名？",
        anchor_low: "Explicitly named in pending bills",
        anchor_low_zh: "在待审法案中被明确点名",
        anchor_high: "No reference in any current legislation",
        anchor_high_zh: "未在任何现行立法中被提及",
        document_hint: "Legislative monitoring report",
      },
      {
        id: "m2_q6",
        text: "Public Sentiment: What is the frequency and tone of negative U.S. news mentions or social media backlash?",
        text_zh: "公众情绪：美国负面新闻报道或社交媒体反弹的频率和基调如何？",
        anchor_low: "Regular negative / hostile coverage",
        anchor_low_zh: "定期负面/敌对报道",
        anchor_high: "Neutral or positive press coverage",
        anchor_high_zh: "中性或正面媒体报道",
        document_hint: "Media sentiment analysis",
      },
      {
        id: "m2_q7",
        text: "Compliance History: Do you have ongoing U.S. regulatory lawsuits, fines, or enforcement actions?",
        text_zh: "合规历史：您是否有正在进行的美国监管诉讼、罚款或执法行动？",
        anchor_low: "Multiple ongoing lawsuits / fines",
        anchor_low_zh: "多起正在进行的诉讼/罚款",
        anchor_high: "No compliance violations",
        anchor_high_zh: "无任何合规违规",
        document_hint: "Regulatory compliance history",
      },
      {
        id: "m2_q8",
        text: "Export Control Risk: Are you involved in sensitive emerging technology subject to EAR controls?",
        text_zh: "出口管制风险：您是否涉及受EAR管制的敏感新兴技术？",
        anchor_low: "Core business involves controlled emerging tech",
        anchor_low_zh: "核心业务涉及受管制的新兴技术",
        anchor_high: "Not subject to EAR",
        anchor_high_zh: "不受EAR约束",
      },
      {
        id: "m2_q9",
        text: "Government / Military Affiliation: Do you hold military contracts or have state-owned enterprise (SOE) status?",
        text_zh: "政府/军方关联：您是否持有军事合同或具有国有企业（SOE）地位？",
        anchor_low: "SOE with active military contracts",
        anchor_low_zh: "具有现役军事合同的国有企业",
        anchor_high: "Fully private with no government affiliation",
        anchor_high_zh: "完全私营且无任何政府关联",
        document_hint: "Ownership structure documentation",
      },
      {
        id: "m2_q10",
        text: "Lobbying Practices: Are your U.S. lobbying activities and political engagements registered under FARA?",
        text_zh: "游说实践：您在美国的游说活动及政治参与是否已依据FARA登记注册？",
        anchor_low: "No registration / hidden influence activities",
        anchor_low_zh: "未登记/隐性影响活动",
        anchor_high: "Full FARA compliance; transparent disclosures",
        anchor_high_zh: "完全符合FARA；信息披露透明",
        document_hint: "FARA registration documents",
      },
    ],
  },
  {
    key: "ip_protection",
    number: 3,
    name: "IP Protection",
    name_zh: "知识产权保护",
    icon: "FileText",
    description: "U.S. patent portfolio, trademark defense, litigation history, and compliance systems",
    description_zh: "美国专利组合、商标保护、诉讼历史及合规体系",
    document_types: [
      "U.S.-registered patents and trademarks",
      "Internal IP compliance manuals",
      "Third-party IP due diligence reports",
      "Licensing and transfer agreement transparency records",
    ],
    questions: [
      {
        id: "m3_q1",
        text: "Patent Coverage: How many active, granted patents do you hold in the USPTO relevant to your core products?",
        text_zh: "专利覆盖：您在USPTO持有多少与核心产品相关的有效授权专利？",
        anchor_low: "No U.S. patents",
        anchor_low_zh: "无美国专利",
        anchor_high: "Strong, core U.S. patent portfolio",
        anchor_high_zh: "强大的核心美国专利组合",
        document_hint: "USPTO patent registration certificates",
      },
      {
        id: "m3_q2",
        text: "Trademark Registration: Do you have active U.S. trademarks and a history of defending them?",
        text_zh: "商标注册：您是否拥有有效的美国商标并有维权记录？",
        anchor_low: "Marks facing cancellation or no registrations",
        anchor_low_zh: "商标面临被注销或未注册",
        anchor_high: "Fully registered and actively defended",
        anchor_high_zh: "已完整注册并积极维权",
        document_hint: "USPTO trademark registration certificates",
      },
      {
        id: "m3_q3",
        text: "Litigation History: Have you been party to U.S. patent, trademark, or copyright lawsuits?",
        text_zh: "诉讼历史：您是否曾作为当事方参与美国专利、商标或版权诉讼？",
        anchor_low: "Multiple unfavorable litigation outcomes",
        anchor_low_zh: "多次败诉记录",
        anchor_high: "Clean record or strong winning history",
        anchor_high_zh: "记录清洁或强劲胜诉历史",
        document_hint: "Litigation history summary",
      },
      {
        id: "m3_q4",
        text: "ITC Section 337 Investigations: Have you ever been subject to a USITC investigation resulting in an exclusion order?",
        text_zh: "ITC第337条调查：您是否曾受到美国国际贸易委员会调查并被下达排除令？",
        anchor_low: "History of exclusion orders",
        anchor_low_zh: "有排除令历史",
        anchor_high: "No ITC investigation history",
        anchor_high_zh: "无ITC调查历史",
        document_hint: "ITC investigation records if applicable",
      },
      {
        id: "m3_q5",
        text: "Internal Compliance: Do you have a documented IP compliance management system and employee training program?",
        text_zh: "内部合规：您是否拥有书面记录的知识产权合规管理体系及员工培训计划？",
        anchor_low: "No formal IP compliance system",
        anchor_low_zh: "无正式知识产权合规体系",
        anchor_high: "Comprehensive audited program in place",
        anchor_high_zh: "已建立经过审计的完善体系",
        document_hint: "IP compliance policy, training records",
      },
      {
        id: "m3_q6",
        text: "Third-Party Due Diligence: Have third-party IP due diligence reports confirmed clean ownership?",
        text_zh: "第三方尽职调查：第三方知识产权尽职调查报告是否确认所有权清晰？",
        anchor_low: "Reports cite red flags or ownership disputes",
        anchor_low_zh: "报告提出红旗警示或所有权争议",
        anchor_high: "Reports confirm strong, clean IP ownership",
        anchor_high_zh: "报告确认知识产权所有权强大且清晰",
        document_hint: "Third-party IP due diligence report",
      },
      {
        id: "m3_q7",
        text: "IP Theft Incidents: Does your company have a history of IP theft allegations or government sanctions related to IP?",
        text_zh: "知识产权盗窃事件：您的公司是否有知识产权盗窃指控或相关政府制裁的历史？",
        anchor_low: "Confirmed sanctions or IP theft history",
        anchor_low_zh: "已确认的制裁或知识产权盗窃历史",
        anchor_high: "No history; positive industry reputation",
        anchor_high_zh: "无历史记录；行业声誉良好",
        document_hint: "Government records, sanctions history",
      },
      {
        id: "m3_q8",
        text: "Licensing Transparency: Are all technology licensing agreements documented and compliant?",
        text_zh: "许可透明度：所有技术许可协议是否均有文件记录且合规？",
        anchor_low: "Opaque or potentially illegal transfers",
        anchor_low_zh: "不透明或潜在违法的转让",
        anchor_high: "Fully documented and legally compliant",
        anchor_high_zh: "完整记录且完全合法合规",
        document_hint: "Technology licensing agreements",
      },
      {
        id: "m3_q9",
        text: "Open Source Usage: Do you have a tracking system ensuring all open-source software is used legally?",
        text_zh: "开源软件使用：您是否有跟踪系统确保所有开源软件的合法使用？",
        anchor_low: "Frequent open-source license violations",
        anchor_low_zh: "频繁违反开源许可证",
        anchor_high: "Robust tracking and compliance system",
        anchor_high_zh: "健全的跟踪与合规体系",
        document_hint: "Open-source software audit",
      },
      {
        id: "m3_q10",
        text: "Peer Risk: How does your IP risk profile compare to industry peers?",
        text_zh: "同行风险：与行业同行相比，您的知识产权风险状况如何？",
        anchor_low: "Significantly higher risk than industry average",
        anchor_low_zh: "风险明显高于行业平均水平",
        anchor_high: "Industry leader in IP protection",
        anchor_high_zh: "知识产权保护领域的行业领先者",
      },
    ],
  },
  {
    key: "data_security",
    number: 4,
    name: "Data Security & Privacy",
    name_zh: "数据安全与隐私",
    icon: "Lock",
    description: "CCPA/CPRA compliance, data localization, NIST framework, and breach protocols",
    description_zh: "CCPA/CPRA合规、数据本地化、NIST框架及数据泄露应对协议",
    document_types: [
      "Corporate privacy policies",
      "Data breach response plans",
      "Contracts showing data localization compliance",
      "Cybersecurity control implementation records",
    ],
    questions: [
      {
        id: "m4_q1",
        text: "CCPA / CPRA Compliance: Does your privacy policy and data handling align with California privacy mandates?",
        text_zh: "CCPA/CPRA合规：您的隐私政策和数据处理是否符合加州隐私法规？",
        anchor_low: "No privacy policy in place",
        anchor_low_zh: "无任何隐私政策",
        anchor_high: "Full compliance with regular third-party audits",
        anchor_high_zh: "完全合规并定期进行第三方审计",
        document_hint: "Privacy policy, CCPA compliance audit",
      },
      {
        id: "m4_q2",
        text: "Breach Notification Protocol: Do you have a tested, documented breach response meeting U.S. legal timelines?",
        text_zh: "数据泄露通知协议：您是否有经过测试、有文件记录且符合美国法律时限的应急响应方案？",
        anchor_low: "History of delayed notifications",
        anchor_low_zh: "有延迟通知的历史记录",
        anchor_high: "Established, regularly tested protocols",
        anchor_high_zh: "已建立并定期测试的应对协议",
        document_hint: "Data breach response plan",
      },
      {
        id: "m4_q3",
        text: "Data Localization: Is all U.S. user data stored or mirrored exclusively within compliant U.S. facilities?",
        text_zh: "数据本地化：所有美国用户数据是否仅存储或镜像于合规的美国设施中？",
        anchor_low: "Data stored exclusively overseas",
        anchor_low_zh: "数据全部存储于境外",
        anchor_high: "All data in compliant U.S. facilities",
        anchor_high_zh: "所有数据存储于合规的美国设施",
        document_hint: "Data storage architecture documentation",
      },
      {
        id: "m4_q4",
        text: "Cybersecurity Framework: Have you implemented a comprehensive security framework such as NIST CSF?",
        text_zh: "网络安全框架：您是否已实施全面的安全框架（如NIST CSF）？",
        anchor_low: "Minimal security measures",
        anchor_low_zh: "安全措施极为有限",
        anchor_high: "NIST-aligned operational framework fully implemented",
        anchor_high_zh: "已全面实施符合NIST标准的运营框架",
        document_hint: "NIST CSF assessment or equivalent certification",
      },
      {
        id: "m4_q5",
        text: "Vendor / Third-Party Risk: Do you perform audits and maintain contractual safeguards for all third-party data processors?",
        text_zh: "供应商/第三方风险：您是否对所有第三方数据处理商进行审计并维持合同保障？",
        anchor_low: "No oversight of third-party processors",
        anchor_low_zh: "对第三方数据处理商无任何监管",
        anchor_high: "Strict contractual safeguards and regular audits",
        anchor_high_zh: "严格的合同保障机制和定期审计",
        document_hint: "Vendor risk management policy",
      },
      {
        id: "m4_q6",
        text: "User Consent Management: Do you have verifiable processes for user data rights and consent?",
        text_zh: "用户同意管理：您是否拥有可核查的用户数据权利与同意流程？",
        anchor_low: "No process for user rights or consent",
        anchor_low_zh: "无任何用户权利或同意流程",
        anchor_high: "Verifiable consent with efficient rights management",
        anchor_high_zh: "可核查的同意机制及高效的权利管理",
        document_hint: "Consent management platform documentation",
      },
      {
        id: "m4_q7",
        text: "Forced Disclosure Risk: Are your U.S. data assets technically and legally isolated from Chinese government disclosure mandates?",
        text_zh: "强制披露风险：您的美国数据资产是否在技术和法律层面与中国政府披露指令隔离？",
        anchor_low: "High risk via China-routed data flows",
        anchor_low_zh: "因数据流经中国而存在高风险",
        anchor_high: "Effective technical and legal isolation",
        anchor_high_zh: "有效的技术和法律隔离措施",
        document_hint: "Data flow architecture, legal opinion on Chinese DSL exposure",
      },
      {
        id: "m4_q8",
        text: "Encryption: Are industry-standard encryption protocols consistently applied to data at rest and in transit?",
        text_zh: "加密：行业标准加密协议是否始终如一地应用于静态和传输中的数据？",
        anchor_low: "Outdated or no encryption",
        anchor_low_zh: "加密过时或未加密",
        anchor_high: "Industry-standard encryption consistently applied",
        anchor_high_zh: "始终采用行业标准加密",
        document_hint: "Encryption policy and implementation documentation",
      },
      {
        id: "m4_q9",
        text: "Employee Security Training: Is mandatory cybersecurity training with assessments in place for all staff?",
        text_zh: "员工安全培训：是否对所有员工实施强制性网络安全培训和考核？",
        anchor_low: "No formal training program",
        anchor_low_zh: "无正式培训计划",
        anchor_high: "Mandatory training with regular assessments",
        anchor_high_zh: "强制性培训并定期考核",
        document_hint: "Training program records",
      },
      {
        id: "m4_q10",
        text: "Incident Response: Do you have a robust, tested recovery strategy for cybersecurity incidents?",
        text_zh: "事件响应：您是否拥有针对网络安全事件的健全且经过测试的恢复策略？",
        anchor_low: "No incident response plan",
        anchor_low_zh: "无事件响应计划",
        anchor_high: "Robust, tested recovery strategies",
        anchor_high_zh: "健全且经过测试的恢复策略",
        document_hint: "Incident response plan, tabletop exercise records",
      },
    ],
  },
  {
    key: "reputational_risk",
    number: 5,
    name: "Reputational Risk",
    name_zh: "声誉风险",
    icon: "Users",
    description: "Media sentiment, consumer trust, CSR programs, and crisis management readiness",
    description_zh: "媒体情绪、消费者信任、企业社会责任项目及危机管理准备",
    document_types: [
      "Corporate Social Responsibility (CSR) reports",
      "Advertising compliance audits",
      "Investor relations communications",
      "Crisis management effectiveness logs",
    ],
    questions: [
      {
        id: "m5_q1",
        text: "Media Tone: What is the predominant tone of U.S. media coverage of your company?",
        text_zh: "媒体基调：美国媒体对您公司报道的主要基调如何？",
        anchor_low: "Predominantly negative / high-volume scandal coverage",
        anchor_low_zh: "以负面/大量丑闻报道为主",
        anchor_high: "Positive or neutral coverage",
        anchor_high_zh: "正面或中性报道",
        document_hint: "Media monitoring / sentiment analysis report",
      },
      {
        id: "m5_q2",
        text: "Social Media Sentiment: Is your brand experiencing social media backlash or boycott campaigns in the U.S.?",
        text_zh: "社交媒体情绪：您的品牌是否在美国遭遇社交媒体反弹或抵制活动？",
        anchor_low: "Active boycotts or widespread backlash",
        anchor_low_zh: "正遭受积极抵制或广泛反弹",
        anchor_high: "Supportive and engaged U.S. audience",
        anchor_high_zh: "美国受众支持度高且参与积极",
        document_hint: "Social media sentiment report",
      },
      {
        id: "m5_q3",
        text: "Consumer Trust Surveys: What do independent U.S. surveys show about brand trust and acceptance?",
        text_zh: "消费者信任调查：独立美国调查对品牌信任度和接受度有何显示？",
        anchor_low: "Low trust / strong negative associations",
        anchor_low_zh: "信任度低/强烈负面关联",
        anchor_high: "High brand loyalty and trust",
        anchor_high_zh: "品牌忠诚度和信任度高",
        document_hint: "Independent consumer survey results",
      },
      {
        id: "m5_q4",
        text: "Regulatory Actions: Do you have unresolved U.S. regulatory investigations or consumer complaints?",
        text_zh: "监管行动：您是否有未解决的美国监管调查或消费者投诉？",
        anchor_low: "Multiple unresolved investigations",
        anchor_low_zh: "多起未解决的调查",
        anchor_high: "Clean regulatory record",
        anchor_high_zh: "监管记录清洁",
        document_hint: "Regulatory action history",
      },
      {
        id: "m5_q5",
        text: "Communication Transparency: How proactive and timely are your public disclosures and crisis communications?",
        text_zh: "信息透明度：您的公开披露和危机沟通是否主动及时？",
        anchor_low: "Opaque or delayed communications",
        anchor_low_zh: "不透明或延迟的沟通",
        anchor_high: "Proactive and timely disclosures",
        anchor_high_zh: "主动及时的信息披露",
        document_hint: "Communications policy, press release history",
      },
      {
        id: "m5_q6",
        text: "CSR Initiatives: Do you have robust, publicized programs aligned with U.S. environmental and labor norms?",
        text_zh: "企业社会责任举措：您是否拥有符合美国环保和劳工标准、并已公开宣传的健全项目？",
        anchor_low: "No CSR or inconsistent with U.S. norms",
        anchor_low_zh: "无企业社会责任项目或与美国标准不符",
        anchor_high: "Robust, well-publicized CSR programs",
        anchor_high_zh: "健全且广泛宣传的企业社会责任项目",
        document_hint: "CSR report or sustainability report",
      },
      {
        id: "m5_q7",
        text: "Activist Opposition: Is there active, organized opposition or boycott threats from U.S. activist groups?",
        text_zh: "活动人士反对：是否有来自美国活动团体的积极、有组织的反对或抵制威胁？",
        anchor_low: "Active, widespread organized opposition",
        anchor_low_zh: "积极、广泛的有组织反对",
        anchor_high: "No significant activist resistance",
        anchor_high_zh: "无显著的活动人士抵制",
      },
      {
        id: "m5_q8",
        text: "Crisis Management: How effectively has your company responded to past negative publicity events?",
        text_zh: "危机管理：您的公司对过去负面公关事件的应对效果如何？",
        anchor_low: "Poor past response; damaged reputation",
        anchor_low_zh: "过去应对不力；声誉受损",
        anchor_high: "Effective responses; reputation restored",
        anchor_high_zh: "应对有效；声誉得以恢复",
        document_hint: "Crisis management framework",
      },
      {
        id: "m5_q9",
        text: "Cultural Alignment: Does your brand messaging align with U.S. consumer values and ethical standards?",
        text_zh: "文化契合度：您的品牌信息是否与美国消费者价值观和道德标准相符？",
        anchor_low: "Messaging conflicts with U.S. norms",
        anchor_low_zh: "品牌信息与美国规范相冲突",
        anchor_high: "Fully aligned on ethics and cultural values",
        anchor_high_zh: "在伦理和文化价值观上完全契合",
      },
      {
        id: "m5_q10",
        text: "Stakeholder Engagement: What is the quality of your relationships with U.S. investors, regulators, and communities?",
        text_zh: "利益相关方参与：您与美国投资者、监管机构和社区的关系质量如何？",
        anchor_low: "Adversarial or non-existent relations",
        anchor_low_zh: "对抗性或不存在的关系",
        anchor_high: "Proactive and cooperative stakeholder engagement",
        anchor_high_zh: "主动且合作的利益相关方参与",
        document_hint: "Investor relations materials, community engagement records",
      },
    ],
  },
  {
    key: "market_access",
    number: 6,
    name: "Market Access",
    name_zh: "市场准入",
    icon: "TrendingUp",
    description: "Tariff impact, non-tariff barriers, distribution access, and regulatory compliance costs",
    description_zh: "关税影响、非关税壁垒、分销渠道准入及合规成本",
    document_types: [
      "Import documentation",
      "Product-specific safety certifications",
      "HTS (Harmonized Tariff Schedule) code categorizations",
      "Market research on consumer preference alignment",
    ],
    questions: [
      {
        id: "m6_q1",
        text: "Tariff Impact: How significantly do Section 301 or other U.S. tariffs affect your product pricing competitiveness?",
        text_zh: "关税影响：301条款或其他美国关税对您产品定价竞争力的影响程度如何？",
        anchor_low: "High tariffs (>15%) severely impact pricing",
        anchor_low_zh: "高关税（>15%）严重影响定价",
        anchor_high: "Negligible or zero tariff impact",
        anchor_high_zh: "关税影响可忽略不计或为零",
        document_hint: "Tariff schedule analysis",
      },
      {
        id: "m6_q2",
        text: "Non-Tariff Barriers: Are you subject to complex import quotas or lengthy technical standard approvals?",
        text_zh: "非关税壁垒：您是否受到复杂进口配额或漫长技术标准审批的约束？",
        anchor_low: "Multiple restrictive non-tariff barriers",
        anchor_low_zh: "多重限制性非关税壁垒",
        anchor_high: "Straightforward compliance with no significant NTBs",
        anchor_high_zh: "合规便捷且无重大非关税壁垒",
      },
      {
        id: "m6_q3",
        text: "Regulatory Compliance Costs: How stringent and costly are U.S. sector-specific compliance requirements for your product?",
        text_zh: "合规成本：美国针对您产品的行业合规要求的严格程度和成本如何？",
        anchor_low: "Stringent and costly requirements",
        anchor_low_zh: "要求严苛且成本高昂",
        anchor_high: "Simple and low-cost compliance pathway",
        anchor_high_zh: "合规途径简单且低成本",
        document_hint: "Regulatory compliance cost analysis",
      },
      {
        id: "m6_q4",
        text: "Market Competition: How entrenched are U.S. competitors and what is the level of local brand loyalty?",
        text_zh: "市场竞争：美国竞争对手的根基有多深厚，本地品牌忠诚度如何？",
        anchor_low: "Dominant entrenched incumbents with high loyalty",
        anchor_low_zh: "强势在位企业占主导且忠诚度高",
        anchor_high: "Clear niche opportunities with low incumbent lock-in",
        anchor_high_zh: "明确的细分市场机会且在位者锁定低",
      },
      {
        id: "m6_q5",
        text: "Consumer Alignment: Does your product require significant adaptation to meet U.S. consumer preferences?",
        text_zh: "消费者契合度：您的产品是否需要大幅调整以满足美国消费者偏好？",
        anchor_low: "Major product and marketing adaptation required",
        anchor_low_zh: "需要大幅调整产品和营销",
        anchor_high: "Minimal adaptation needed",
        anchor_high_zh: "几乎无需调整",
      },
      {
        id: "m6_q6",
        text: "Distribution Access: Do you have established U.S. distribution partners and retail network access?",
        text_zh: "分销渠道准入：您是否已建立美国分销合作伙伴关系和零售网络准入？",
        anchor_low: "Limited or no distribution access",
        anchor_low_zh: "分销渠道有限或无",
        anchor_high: "Wide, readily available distribution partnerships",
        anchor_high_zh: "广泛且现成的分销合作伙伴关系",
        document_hint: "Distribution partner agreements",
      },
      {
        id: "m6_q7",
        text: "IP Protection Environment: How robust is U.S. enforcement of your IP rights in your market segment?",
        text_zh: "知识产权保护环境：美国在您所在市场领域对知识产权的执法力度如何？",
        anchor_low: "Weak protection or high infringement risk",
        anchor_low_zh: "保护力度弱或侵权风险高",
        anchor_high: "Strong U.S. enforcement environment",
        anchor_high_zh: "美国执法环境严格有力",
      },
      {
        id: "m6_q8",
        text: "Cultural / Language Barriers: How prepared is your organization for U.S. cultural and language requirements?",
        text_zh: "文化/语言障碍：您的组织对美国文化和语言要求的准备程度如何？",
        anchor_low: "Significant cultural and language barriers",
        anchor_low_zh: "存在重大文化和语言障碍",
        anchor_high: "Bilingual team, well-prepared for localization",
        anchor_high_zh: "双语团队，充分准备好本地化",
      },
      {
        id: "m6_q9",
        text: "Policy Stability: What is the risk of sudden U.S. policy changes adversely affecting your market access?",
        text_zh: "政策稳定性：美国政策突变对您市场准入产生不利影响的风险有多大？",
        anchor_low: "High risk of sudden adverse policy changes",
        anchor_low_zh: "政策突然不利变化的风险高",
        anchor_high: "Predictable and stable trade environment",
        anchor_high_zh: "可预期且稳定的贸易环境",
      },
      {
        id: "m6_q10",
        text: "Customs Complexity: How efficient and accurate are your U.S. customs and import procedures?",
        text_zh: "海关复杂性：您的美国海关和进口程序的效率和准确性如何？",
        anchor_low: "Frequent delays and costly errors",
        anchor_low_zh: "频繁延误且错误成本高",
        anchor_high: "Efficient, fully CBP-compliant procedures",
        anchor_high_zh: "高效且完全符合CBP要求的程序",
        document_hint: "Customs compliance audit, CBP rulings",
      },
    ],
  },
  {
    key: "supply_chain",
    number: 7,
    name: "Supply Chain",
    name_zh: "供应链",
    icon: "Truck",
    description: "Origin traceability, forced labor compliance, supplier diversification, and logistics security",
    description_zh: "原产地可追溯性、强迫劳动合规、供应商多元化及物流安全",
    document_types: [
      "Origin of goods documentation",
      "Supplier codes of conduct",
      "Tier 1–3 supply chain mapping",
      "CTPAT (Customs-Trade Partnership Against Terrorism) security protocols",
    ],
    questions: [
      {
        id: "m7_q1",
        text: "Origin Transparency: Can you provide a full audit trail for raw materials down to Tier 3 suppliers?",
        text_zh: "原产地透明度：您能否提供追溯至三级供应商的完整原材料审计链？",
        anchor_low: "No traceability beyond Tier 1",
        anchor_low_zh: "无法追溯至一级供应商以外",
        anchor_high: "Full raw material records to Tier 3+",
        anchor_high_zh: "原材料记录完整追溯至三级及以上",
        document_hint: "Supply chain mapping documentation",
      },
      {
        id: "m7_q2",
        text: "Forced Labor Risk: Do you have verified records proving goods are not linked to forced labor in Xinjiang (UFLPA)?",
        text_zh: "强迫劳动风险：您是否有经核实的记录证明商品与新疆强迫劳动无关（UFLPA）？",
        anchor_low: "No due diligence; Xinjiang exposure risk",
        anchor_low_zh: "无尽职调查；存在新疆风险敞口",
        anchor_high: "Real-time UFLPA compliance with verified records",
        anchor_high_zh: "实时UFLPA合规并有经核实的记录",
        document_hint: "UFLPA compliance documentation, supplier certifications",
      },
      {
        id: "m7_q3",
        text: "Supplier Diversification: What percentage of critical components rely on a single country or region?",
        text_zh: "供应商多元化：关键零部件对单一国家或地区的依赖比例是多少？",
        anchor_low: ">80% reliance on a single region",
        anchor_low_zh: ">80%依赖单一地区",
        anchor_high: "Multiple-country sourcing with no single dependency",
        anchor_high_zh: "多国采购且无单点依赖",
        document_hint: "Supplier diversification report",
      },
      {
        id: "m7_q4",
        text: "Sanctions Compliance: Do you have automated screening to ensure no sanctioned suppliers are used?",
        text_zh: "制裁合规：您是否有自动筛查系统确保不使用受制裁供应商？",
        anchor_low: "Sanctioned suppliers used without screening",
        anchor_low_zh: "未经筛查使用受制裁供应商",
        anchor_high: "Automated, real-time sanctions screening in place",
        anchor_high_zh: "已部署自动化实时制裁筛查系统",
        document_hint: "Sanctions screening system documentation",
      },
      {
        id: "m7_q5",
        text: "Supply Chain Cybersecurity: Are your logistics and inventory systems NIST/CISA compliant?",
        text_zh: "供应链网络安全：您的物流和库存系统是否符合NIST/CISA标准？",
        anchor_low: "Vulnerable logistics systems with known gaps",
        anchor_low_zh: "物流系统存在已知漏洞",
        anchor_high: "NIST/CISA compliant platforms throughout",
        anchor_high_zh: "全程采用符合NIST/CISA标准的平台",
        document_hint: "Supply chain cybersecurity assessment",
      },
      {
        id: "m7_q6",
        text: "Customs Readiness: Are all U.S. customs filings accurate and CBP-compliant with minimal delays?",
        text_zh: "海关准备：所有美国海关申报是否准确、符合CBP要求且延误极少？",
        anchor_low: "Frequent delays and errors",
        anchor_low_zh: "频繁延误和错误",
        anchor_high: "All filings accurate and CBP-compliant",
        anchor_high_zh: "所有申报准确且符合CBP要求",
        document_hint: "Customs compliance history",
      },
      {
        id: "m7_q7",
        text: "Ethical / Green Sourcing: Do you have certified ethical and environmental sourcing practices?",
        text_zh: "道德/绿色采购：您是否拥有经认证的道德和环保采购实践？",
        anchor_low: "No environmental or ethical audits",
        anchor_low_zh: "无任何环保或道德审计",
        anchor_high: "Third-party certified green and ethical sourcing",
        anchor_high_zh: "经第三方认证的绿色和道德采购",
        document_hint: "Ethical sourcing certifications",
      },
      {
        id: "m7_q8",
        text: "Contingency Planning: Do you have tested alternate supplier plans for critical components?",
        text_zh: "应急规划：您是否为关键零部件制定了经过测试的备用供应商计划？",
        anchor_low: "No alternate suppliers identified",
        anchor_low_zh: "未识别任何备用供应商",
        anchor_high: "Multiple tested contingency supplier plans",
        anchor_high_zh: "多个经过测试的应急供应商计划",
        document_hint: "Business continuity plan",
      },
      {
        id: "m7_q9",
        text: "Secure Logistics: Are your transportation and warehousing practices compliant with the CTPAT program?",
        text_zh: "安全物流：您的运输和仓储实践是否符合CTPAT计划要求？",
        anchor_low: "No secure logistics protocols",
        anchor_low_zh: "无安全物流协议",
        anchor_high: "Full CTPAT participation and certification",
        anchor_high_zh: "全面参与并获得CTPAT认证",
        document_hint: "CTPAT certification",
      },
      {
        id: "m7_q10",
        text: "Strategic Industry Risk: Is your supply chain concentrated in sectors facing high U.S. scrutiny (e.g., semiconductors)?",
        text_zh: "战略行业风险：您的供应链是否集中在受美国高度审查的行业（如半导体）？",
        anchor_low: "High exposure in strategically sensitive sectors",
        anchor_low_zh: "在战略敏感行业高度集中",
        anchor_high: "No involvement in high-scrutiny strategic sectors",
        anchor_high_zh: "不涉及任何高审查战略行业",
      },
    ],
  },
  {
    key: "financial_risks",
    number: 8,
    name: "Financial & Economic Risks",
    name_zh: "财务与经济风险",
    icon: "DollarSign",
    description: "Currency hedging, PCAOB audit compliance, SEC readiness, and capital structure resilience",
    description_zh: "货币对冲、PCAOB审计合规、SEC准备及资本结构韧性",
    document_types: [
      "SEC filings (Forms F-1 or 20-F)",
      "Currency hedging strategy records",
      "SOX (Sarbanes-Oxley Act) internal control attestations",
      "U.S. banking relationship records",
    ],
    questions: [
      {
        id: "m8_q1",
        text: "Currency Hedging: Do you have a management plan or financial tools (swaps, forwards) to handle RMB-USD volatility?",
        text_zh: "货币对冲：您是否拥有应对人民币-美元汇率波动的管理方案或金融工具（掉期、远期合约）？",
        anchor_low: "No hedging strategy in place",
        anchor_low_zh: "无任何对冲策略",
        anchor_high: "Comprehensive FX management plan and instruments",
        anchor_high_zh: "全面的外汇管理方案及工具",
        document_hint: "FX risk management policy",
      },
      {
        id: "m8_q2",
        text: "Capital Market Readiness: Are your financials compliant with SEC rules and prepared for U.S. market scrutiny?",
        text_zh: "资本市场准备：您的财务信息是否符合SEC规定并已准备好接受美国市场审查？",
        anchor_low: "No SEC preparation or compliance",
        anchor_low_zh: "无SEC准备或合规",
        anchor_high: "Fully SEC-compliant and audit-ready",
        anchor_high_zh: "完全符合SEC要求并已准备好审计",
        document_hint: "SEC Form 20-F or equivalent",
      },
      {
        id: "m8_q3",
        text: "Audit Standards: Is your external auditor registered with and in good standing with the PCAOB?",
        text_zh: "审计标准：您的外部审计机构是否在PCAOB注册且信誉良好？",
        anchor_low: "Non-registered auditor used",
        anchor_low_zh: "使用未注册的审计机构",
        anchor_high: "Clean PCAOB audit opinion from registered firm",
        anchor_high_zh: "来自注册机构的清洁PCAOB审计意见",
        document_hint: "PCAOB-audited financial statements",
      },
      {
        id: "m8_q4",
        text: "Federal Policy Impact: How exposed is your capital structure to U.S. interest rate hikes or monetary tightening?",
        text_zh: "联邦政策影响：您的资本结构对美国加息或货币紧缩的敞口有多大？",
        anchor_low: "Highly leveraged with no contingency",
        anchor_low_zh: "高杠杆且无应急预案",
        anchor_high: "Balanced capital structure with adequate buffers",
        anchor_high_zh: "均衡的资本结构并有充足缓冲",
        document_hint: "Capital structure analysis, stress test results",
      },
      {
        id: "m8_q5",
        text: "Financial / Capital Barriers: Are there restrictions on moving capital between your U.S. and Chinese operations?",
        text_zh: "财务/资本障碍：美中业务间的资本流动是否存在限制？",
        anchor_low: "Significant capital movement restrictions",
        anchor_low_zh: "存在重大资本流动限制",
        anchor_high: "Structurally tax-efficient with free capital flow",
        anchor_high_zh: "结构上税务高效且资本可自由流动",
        document_hint: "Legal opinion on capital repatriation",
      },
      {
        id: "m8_q6",
        text: "Trade / Tariff Exposure: How significantly do U.S. tariffs impact your core product line's financial performance?",
        text_zh: "贸易/关税敞口：美国关税对您核心产品线财务表现的影响程度如何？",
        anchor_low: "Core products heavily tariffed; no mitigation",
        anchor_low_zh: "核心产品税率高且无缓解措施",
        anchor_high: "Supply chain restructured to minimize tariff impact",
        anchor_high_zh: "供应链已重组以最大限度降低关税影响",
        document_hint: "Tariff impact analysis",
      },
      {
        id: "m8_q7",
        text: "CFIUS / National Security Financial Risk: Has your financial profile in high-risk sectors (AI, chips) been reviewed by counsel?",
        text_zh: "CFIUS/国家安全财务风险：您在高风险行业（人工智能、芯片）的财务状况是否已经法律顾问审查？",
        anchor_low: "High-risk sector with no legal review",
        anchor_low_zh: "高风险行业且无法律审查",
        anchor_high: "Pre-reviewed by qualified CFIUS counsel",
        anchor_high_zh: "已由具备资质的CFIUS顾问预先审查",
        document_hint: "CFIUS counsel opinion letter",
      },
      {
        id: "m8_q8",
        text: "Reporting Transparency: Are your accounts reconciled under both PRC and U.S. GAAP (or IFRS)?",
        text_zh: "报告透明度：您的账目是否已按中国会计准则和美国GAAP（或IFRS）双重核对？",
        anchor_low: "Opaque GAAP divergence",
        anchor_low_zh: "GAAP差异不透明",
        anchor_high: "Transparent, reconciled dual-standard accounts",
        anchor_high_zh: "透明且经双重核对的账目",
        document_hint: "Dual GAAP reconciliation report",
      },
      {
        id: "m8_q9",
        text: "U.S. Banking Infrastructure: Do you have established U.S. banking relationships and credit access?",
        text_zh: "美国银行基础设施：您是否已建立美国银行关系和信贷渠道？",
        anchor_low: "No U.S. banking relationships or credit access",
        anchor_low_zh: "无任何美国银行关系或信贷渠道",
        anchor_high: "Established revolving U.S. credit lines",
        anchor_high_zh: "已建立循环美国信贷额度",
        document_hint: "U.S. banking relationship documentation",
      },
      {
        id: "m8_q10",
        text: "Economic Resilience: Have you conducted stress tests for the impact of U.S. inflation or economic downturns?",
        text_zh: "经济韧性：您是否已就美国通胀或经济下行的影响进行压力测试？",
        anchor_low: "Highly exposed with no stress testing",
        anchor_low_zh: "高度暴露且无压力测试",
        anchor_high: "Proven margin flexibility and economic elasticity",
        anchor_high_zh: "已验证的利润弹性和经济适应性",
        document_hint: "Economic stress test results",
      },
    ],
  },
  {
    key: "national_security",
    number: 9,
    name: "National Security",
    name_zh: "国家安全",
    icon: "ShieldAlert",
    description: "Dual-use technology risk, critical infrastructure proximity, and technology transfer controls",
    description_zh: "两用技术风险、关键基础设施邻近性及技术转让管控",
    document_types: [
      "Export control compliance manuals",
      "R&D partnership grant disclosures",
      "Cybersecurity access protocols for remote or cloud systems",
    ],
    questions: [
      {
        id: "m9_q1",
        text: "Critical Technology Involvement: Is your company directly involved in AI, quantum computing, or advanced robotics?",
        text_zh: "关键技术参与：您的公司是否直接涉及人工智能、量子计算或先进机器人技术？",
        anchor_low: "Direct involvement in most sensitive categories",
        anchor_low_zh: "直接涉及最敏感的技术类别",
        anchor_high: "No involvement in critical technology areas",
        anchor_high_zh: "不涉及任何关键技术领域",
        document_hint: "Product / technology description",
      },
      {
        id: "m9_q2",
        text: "Dual-Use Risk: Can your technologies be easily repurposed for military, intelligence, or surveillance applications?",
        text_zh: "两用风险：您的技术是否容易被转用于军事、情报或监控应用？",
        anchor_low: "Easily repurposed for military or surveillance use",
        anchor_low_zh: "容易被转用于军事或监控",
        anchor_high: "Single-use civilian application only",
        anchor_high_zh: "仅限单一民用应用",
        document_hint: "Dual-use technology assessment",
      },
      {
        id: "m9_q3",
        text: "State Control: Is your company fully private, or are there embedded state ownership or CCP units?",
        text_zh: "国家控制：您的公司是否完全私营，或是否存在嵌入式国家所有权或中共党组？",
        anchor_low: "State-owned or CCP units embedded",
        anchor_low_zh: "国有或内嵌中共党组",
        anchor_high: "Fully private with verifiable independence",
        anchor_high_zh: "完全私营且可核实独立性",
        document_hint: "Corporate governance documentation",
      },
      {
        id: "m9_q4",
        text: "Entity List Risk: Are you or your key affiliates at risk of listing on major U.S. watch lists?",
        text_zh: "实体清单风险：您或您的主要关联方是否面临被列入美国主要监控名单的风险？",
        anchor_low: "Currently listed on major watch lists",
        anchor_low_zh: "当前已列于主要监控名单",
        anchor_high: "No current or anticipated sanctions exposure",
        anchor_high_zh: "无当前或预期的制裁风险敞口",
        document_hint: "Sanctions risk assessment",
      },
      {
        id: "m9_q5",
        text: "Infrastructure Proximity: Is your business physically or digitally integrated with U.S. telecom, power, or defense systems?",
        text_zh: "基础设施邻近性：您的业务是否在物理或数字层面与美国电信、电力或国防系统相整合？",
        anchor_low: "Deeply integrated with critical U.S. networks",
        anchor_low_zh: "与美国关键网络深度整合",
        anchor_high: "No proximity to or integration with sensitive sites",
        anchor_high_zh: "不邻近或整合任何敏感场所",
        document_hint: "Facility maps, network architecture diagrams",
      },
      {
        id: "m9_q6",
        text: "U.S. Data Access: Does your company handle large volumes of sensitive U.S. personal data (health, biometric, financial)?",
        text_zh: "美国数据访问：您的公司是否处理大量敏感的美国个人数据（健康、生物特征、财务）？",
        anchor_low: "Handles large volumes of sensitive biometric / health data",
        anchor_low_zh: "处理大量敏感生物特征/健康数据",
        anchor_high: "No sensitive U.S. personal data collected",
        anchor_high_zh: "不收集任何敏感美国个人数据",
        document_hint: "Data inventory and classification",
      },
      {
        id: "m9_q7",
        text: "Export Compliance Infrastructure: How mature is your export compliance program, and do you have a history of violations?",
        text_zh: "出口合规基础设施：您的出口合规项目成熟度如何，是否有违规历史？",
        anchor_low: "History of export violations or evasion",
        anchor_low_zh: "有出口违规或规避历史",
        anchor_high: "Mature compliance infrastructure with clean record",
        anchor_high_zh: "成熟的合规基础设施且记录清洁",
        document_hint: "Export compliance program documentation",
      },
      {
        id: "m9_q8",
        text: "CFIUS History: Has your company had prior CFIUS interventions, forced divestitures, or repeated rejections?",
        text_zh: "CFIUS历史：您的公司是否有过CFIUS干预、强制剥离或反复被拒的历史？",
        anchor_low: "Repeated CFIUS rejections or divestitures",
        anchor_low_zh: "反复遭CFIUS拒绝或被迫剥离",
        anchor_high: "No prior CFIUS intervention",
        anchor_high_zh: "无任何CFIUS干预历史",
        document_hint: "CFIUS history documentation",
      },
      {
        id: "m9_q9",
        text: "Research Collaboration: Do you engage in joint R&D with U.S. universities or labs without documented security safeguards?",
        text_zh: "研究合作：您是否在无书面安全保障的情况下与美国大学或实验室开展联合研发？",
        anchor_low: "Unprotected collaboration in defense-adjacent research",
        anchor_low_zh: "在国防相关研究中无保护的合作",
        anchor_high: "No joint research or fully safeguarded partnerships",
        anchor_high_zh: "无联合研究或完全有保障的合作关系",
        document_hint: "Research collaboration agreements",
      },
      {
        id: "m9_q10",
        text: "Personnel / Technology Transfer: Is there a technical firewall preventing unrestricted technology flow between U.S. and PRC operations?",
        text_zh: "人员/技术转让：是否存在技术防火墙防止美国和中国业务之间无限制的技术流动？",
        anchor_low: "Unrestricted technology and personnel transfer",
        anchor_low_zh: "技术和人员转移不受限制",
        anchor_high: "Strong jurisdictional separation enforced",
        anchor_high_zh: "严格执行司法管辖区分离",
        document_hint: "Technology transfer control policy",
      },
    ],
  },
  {
    key: "corporate_governance",
    number: 10,
    name: "Corporate Governance",
    name_zh: "公司治理",
    icon: "Building2",
    description: "Board independence, audit transparency, HFCAA compliance, and shareholder rights",
    description_zh: "董事会独立性、审计透明度、HFCAA合规及股东权利",
    document_types: [
      "Corporate charters and bylaws",
      "Board composition reports",
      "Whistleblower protection policies",
      "Detailed related-party transaction disclosures",
    ],
    questions: [
      {
        id: "m10_q1",
        text: "Board Independence: Is the majority of your board independent, and are audit committees independently staffed?",
        text_zh: "董事会独立性：您的董事会是否多数为独立董事，审计委员会是否独立配置？",
        anchor_low: "Board dominated by insiders",
        anchor_low_zh: "董事会由内部人士主导",
        anchor_high: "Majority independent members with independent audit committee",
        anchor_high_zh: "多数为独立成员且审计委员会独立",
        document_hint: "Board composition report, director bios",
      },
      {
        id: "m10_q2",
        text: "Audit Oversight (HFCAA): Do you allow U.S. regulators full inspection of your audit working papers?",
        text_zh: "审计监督（HFCAA）：您是否允许美国监管机构全面检查审计工作底稿？",
        anchor_low: "Audit working papers denied to U.S. regulators",
        anchor_low_zh: "拒绝美国监管机构查阅审计工作底稿",
        anchor_high: "Fully PCAOB-compliant with unrestricted access",
        anchor_high_zh: "完全符合PCAOB要求且提供无限制访问",
        document_hint: "PCAOB inspection correspondence",
      },
      {
        id: "m10_q3",
        text: "Disclosure Quality: Are your SEC filings and financial disclosures timely, complete, and reconciled?",
        text_zh: "披露质量：您的SEC文件和财务披露是否及时、完整且经过核对？",
        anchor_low: "Frequently late or misleading disclosures",
        anchor_low_zh: "频繁延迟或具有误导性的披露",
        anchor_high: "Timely, accurate, SEC-reconciled accounts",
        anchor_high_zh: "及时、准确且经SEC核对的账目",
        document_hint: "SEC filing history",
      },
      {
        id: "m10_q4",
        text: "Internal Controls (ICFR): Is your internal financial reporting system independently validated and CEO/CFO certified?",
        text_zh: "内部控制（ICFR）：您的内部财务报告体系是否经过独立验证并由CEO/CFO认证？",
        anchor_low: "No ICFR disclosures or certification",
        anchor_low_zh: "无ICFR披露或认证",
        anchor_high: "Independently validated and annually certified",
        anchor_high_zh: "经独立验证并每年认证",
        document_hint: "SOX 302/404 certifications",
      },
      {
        id: "m10_q5",
        text: "Political Connections: Are board members or executives free from undisclosed CCP connections or political influence?",
        text_zh: "政治关联：董事会成员或高管是否不存在未披露的中共关联或政治影响？",
        anchor_low: "Hidden CCP units or political influence",
        anchor_low_zh: "隐藏的中共组织或政治影响",
        anchor_high: "Transparent firewall from political connections",
        anchor_high_zh: "与政治关联保持透明的防火墙",
        document_hint: "Director conflict of interest disclosures",
      },
      {
        id: "m10_q6",
        text: "Executive Compensation: Are executive pay structures transparent, itemized, and linked to performance?",
        text_zh: "高管薪酬：高管薪酬结构是否透明、逐项列示且与绩效挂钩？",
        anchor_low: "Opaque bonus structures with no public disclosure",
        anchor_low_zh: "不透明的奖金结构且无公开披露",
        anchor_high: "Itemized, performance-linked compensation disclosed",
        anchor_high_zh: "逐项列示、与绩效挂钩的薪酬已披露",
        document_hint: "Executive compensation disclosures",
      },
      {
        id: "m10_q7",
        text: "Whistleblower Protections: Do you have an anonymous, independent whistleblower program with no retaliation history?",
        text_zh: "举报人保护：您是否拥有匿名、独立的举报计划且无报复历史？",
        anchor_low: "No policy or confirmed retaliation incidents",
        anchor_low_zh: "无政策或已确认的报复事件",
        anchor_high: "Anonymous, independent program with strong protection",
        anchor_high_zh: "匿名独立计划且保护力度强",
        document_hint: "Whistleblower policy documentation",
      },
      {
        id: "m10_q8",
        text: "Related-Party Transactions: Are all deals involving shareholders, executives, or state entities disclosed and approved by independent directors?",
        text_zh: "关联方交易：所有涉及股东、高管或国家实体的交易是否均已披露并经独立董事批准？",
        anchor_low: "Frequent undisclosed related-party transactions",
        anchor_low_zh: "频繁的未披露关联方交易",
        anchor_high: "All deals approved by independent directors",
        anchor_high_zh: "所有交易均经独立董事批准",
        document_hint: "Related-party transaction disclosures",
      },
      {
        id: "m10_q9",
        text: "Shareholder Rights: Do you operate under a one-share-one-vote policy, or is control concentrated via dual-class shares?",
        text_zh: "股东权利：您是否采用同股同权政策，或控制权是否通过双重股权结构集中？",
        anchor_low: "Control concentrated via dual-class shares",
        anchor_low_zh: "控制权通过双重股权结构集中",
        anchor_high: "One-share-one-vote policy in place",
        anchor_high_zh: "已实施同股同权政策",
        document_hint: "Corporate charter, share structure documentation",
      },
      {
        id: "m10_q10",
        text: "ESG Governance: Does your board have a dedicated ESG risk committee with diverse membership?",
        text_zh: "ESG治理：您的董事会是否设有专门的ESG风险委员会且成员多元化？",
        anchor_low: "No ESG oversight or board diversity",
        anchor_low_zh: "无ESG监督或董事会多元化",
        anchor_high: "Diverse board with active ESG risk committee",
        anchor_high_zh: "多元化董事会且设有积极运作的ESG风险委员会",
        document_hint: "ESG report, board committee charters",
      },
    ],
  },
]

export function getModuleByKey(key: string): Module | undefined {
  return ASSESSMENT_MODULES.find((m) => m.key === key)
}

export function getModuleByNumber(number: number): Module | undefined {
  return ASSESSMENT_MODULES.find((m) => m.number === number)
}

export const MODULE_KEYS = ASSESSMENT_MODULES.map((m) => m.key)
export const TOTAL_QUESTIONS = ASSESSMENT_MODULES.length * 10
